# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).

# Blank Stadium: Stadium.create(name: "", address: "", city: "", country: "", home_team: "", primary_sport: "", primary_competition: "", capacity: , image: "")

# Premier League
# Stadium.create(name: "Etihad Stadium", address: "Ashton New Rd, Manchester M11 3FF, United Kingdom", city: "Manchester", country: "United Kingdom", home_team: "Manchester City", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 55017, image: "https://www.thestadiumbusiness.com/wp-content/uploads/2019/10/Etihad_Stadium-1-3.jpg")
# Stadium.create(name: "Old Trafford", address: "Sir Matt Busby Way, Old Trafford, Stretford, Manchester M16 0RA, United Kingdom", city: "Manchester", country: "United Kingdom", home_team: "Manchester United", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 75643, image: "https://img.fifa.com/image/upload/t_l1/c66wodrhc27coham0zkz.jpg")
# Stadium.create(name: "Stamford Bridge", address: "Fulham Rd, London SW6 1HS, United Kingdom", city: "London", country: "United Kingdom", home_team: "Chelsea", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 40834, image: "https://images2.minutemediacdn.com/image/fetch/w_736,h_485,c_fill,g_auto,f_auto/https%3A%2F%2Ftheprideoflondon.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2016%2F03%2F514524892-chelsea-fc-v-paris-saint-germain-uefa-champions-league-850x560.jpg")
# Stadium.create(name: "King Power Stadium", address: "Filbert Way, Leicester LE2 7FL, United Kingdom", city: "Leicester", country: "United Kingdom", home_team: "Leicester City", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32261, image: "https://www.leicestercity.net/wp-content/uploads/2020/11/king-power.jpg")
# Stadium.create(name: "London Stadium", address: "London E20 2ST, United Kingdom", city: "London", country: "United Kingdom", home_team: "West Ham", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 60000, image: "https://res.cloudinary.com/london-stadium/image/upload/assets/main_image/1595350248_graciolli_img_8022-hdr.jpg")
# Stadium.create(name: "Anfield", address: "Anfield Rd, Anfield, Liverpool L4 0TH, United Kingdom", city: "Liverpool", country: "United Kingdom", home_team: "Liverpool", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 54074, image: "https://i.ytimg.com/vi/6-83IeF56r4/maxresdefault.jpg")
# Stadium.create(name: "Tottenham Hotspur Stadium", address: "782 High Rd, London N17 0BX, United Kingdom", city: "London", country: "United Kingdom", home_team: "Tottenham Hotspur", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 62214, image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Tottenham_Hotspur_Stadium_South_Stand.jpg")
# Stadium.create(name: "Villa Park", address: "Trinity Rd, Birmingham B6 6HE, United Kingdom", city: "Birmingham", country: "United Kingdom", home_team: "Aston Villa", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 42749, image: "https://i.guim.co.uk/img/media/4b89d8784cbd2bc089c1229cf5285ba276c177b2/0_339_5095_3057/master/5095.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=e4a2f64db8b09ba3f167099d37a04173")
# Stadium.create(name: "St. James' Park", address: "Barrack Rd, Newcastle upon Tyne NE1 4ST, United Kingdom", city: "Newcastle upon Tyne", country: "United Kingdom", home_team: "Newcastle United", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 52305, image: "https://www.nufc.co.uk/media/24154/st-james-hero-image.jpg?anchor=center&mode=crop&width=900&height=506&quality=75")
# Stadium.create(name: "Craven Cottage", address: "Stevenage Rd, London SW6 6HH, United Kingdom", city: "London", country: "United Kingdom", home_team: "Fulham", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 25700, image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Craven_Cottage_stadium_view.jpg")
# ~~~~~~~~~~~~~~~~~~~~~ (Everything above here has been created already)
# Stadium.create(name: "Turf Moor", address: "52-56 Harry Potts Way, Burnley BB10 4BX, United Kingdom", city: "Burnley", country: "United Kingdom", home_team: "Burnley", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 21944, image: "https://stadiumjourney.com/wp-content/uploads/2011/01/Turf-Moor-Jonathan-Morritt.jpg")
# Stadium.create(name: "Goodison Park", address: "Goodison Rd, Liverpool L4 4EL, United Kingdom", city: "Liverpool", country: "United Kingdom", home_team: "Everton", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 39414, image: "https://specials-images.forbesimg.com/imageserve/1206897856/960x0.jpg?fit=scale")
# Stadium.create(name: "Selhurst Park", address: "Whitehorse Ln, London SE25 6PU, United Kingdom", city: "London", country: "United Kingdom", home_team: "Crystal Palace", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 25486, image: "https://media3.minutemediacdn.com/process?url=https%3A%2F%2F90min-images-original.s3.amazonaws.com%2Fproduction%2Fcrystal-palace-v-afc-bournemouth-premier-league-5e9b14458b1b39886b000001.jpg&filters%5Bcrop%5D%5Bw%5D=0.8888888888888888&filters%5Bcrop%5D%5Bh%5D=1.0&filters%5Bcrop%5D%5Bo_x%5D=0.05904761904761905&filters%5Bcrop%5D%5Bo_y%5D=0.0&filters%5Bquality%5D%5Btarget%5D=80&type=.jpg&filters%5Bresize%5D%5Bw%5D=630&filters%5Bresize%5D%5Bh%5D=472")
# Stadium.create(name: "Emirates Stadium", address: "Hornsey Rd, London N7 7AJ, United Kingdom", city: "London", country: "United Kingdom", home_team: "Arsenal", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 60704, image: "https://i.pinimg.com/originals/38/64/82/3864822cfb3ac3116c596e6b08108603.jpg")
# Stadium.create(name: "Molineux Stadium", address: "Waterloo Rd, Wolverhampton WV1 4QR, United Kingdom", city: "Wolverhampton", country: "United Kingdom", home_team: "Wolves", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32050, image: "https://events.wolves.co.uk/wp-content/uploads/2020/04/Molineux-Fireworks.jpg")
# Stadium.create(name: "Elland Road", address: "Elland Rd, Beeston, Leeds LS11 0ES, United Kingdom", city: "Leeds", country: "United Kingdom", home_team: "Leeds", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 37792, image: "https://www.footballfancast.com/wp-content/uploads/2020/07/Elland-Road.jpg")
# Stadium.create(name: "The American Express Community Stadium", address: "Village Way, Brighton BN1 9BL, United Kingdom", city: "Brighton", country: "United Kingdom", home_team: "Brighton", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 30750, image: "https://resources.premierleague.com/premierleague/photo/2020/08/27/003795da-d99f-42ea-8501-ca9c0c8bac85/BHA-AMex-Stadium-general-view.jpg")
# Stadium.create(name: "St. Mary's Stadium", address: "Britannia Rd, Southampton SO14 5FP, United Kingdom", city: "Southampton", country: "United Kingdom", home_team: "Southampton", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32384, image: "https://www.musco.com/wp-content/uploads/2019/06/southampton_1200x600.jpg")
# Stadium.create(name: "The Hawthorns", address: "West Bromwich B71 4LF, United Kingdom", city: "West Bromwich", country: "United Kingdom", home_team: "West Brom", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 26445, image: "https://cdn.swanseacity.com/sites/default/files/archive/21x9%20WBA%20THE%20HAWTHORNS.jpg")
# Stadium.create(name: "Bramall Lane", address: "Bramall Ln, Highfield, Sheffield S2 4SU, United Kingdom", city: "Sheffield", country: "United Kingdom", home_team: "Sheffield United", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32702, image: "https://s3.eu-west-1.amazonaws.com/gc-media-assets.gc.sheffieldunited.co.uk/8c82c028-8a22-4053-8a2e-62e6c2366636.jpg")

# MLB
Stadium.create(name: "Dodger Stadium", address: "1000 Vin Scully Ave, Los Angeles, CA 90012", city: "Los Angeles", country: "USA", home_team: "Los Angeles Dodgers", primary_sport: "Baseball", primary_competition: "MLB", capacity: 56000, image: "https://www.travelcaffeine.com/wp-content/uploads/2020/07/los-angeles-dodger-stadium-southern-california-235.jpg")
Stadium.create(name: "Rogers Centre", address: "1 Blue Jays Way, Toronto, ON M5V 1J1, Canada", city: "Toronto", country: "Canada", home_team: "Toronto Blue Jays", primary_sport: "Baseball", primary_competition: "MLB", capacity: 53506, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/rogers179532.jpg")
Stadium.create(name: "Yankee Stadium", address: "", city: "New York City", country: "USA", home_team: "New York Yankees", primary_sport: "Baseball", primary_competition: "MLB", capacity: 52325, image: "https://empiresportsmedia.com/wp-content/uploads/2020/07/yankeestadiumairal.jpg")
Stadium.create(name: "Coors Field", address: "", city: "Denver", country: "USA", home_team: "Colorado Rockies", primary_sport: "Baseball", primary_competition: "MLB", capacity: 50144, image: "https://gray-kktv-prod.cdn.arcpublishing.com/resizer/N6ene9-l0qL_ABbL-9kSdVvmj8E=/1200x675/smart/cloudfront-us-east-1.images.arcpublishing.com/gray/7D2PNULBTNGTNAK2SMSYAU5TQY.jpg")
Stadium.create(name: "Chase Field", address: "", city: "Phoenix", country: "USA", home_team: "Arizona Diamondbacks", primary_sport: "Baseball", primary_competition: "MLB", capacity: 48686, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/chase_topv2.jpg")
Stadium.create(name: "T-Mobile Park", address: "", city: "Seattle", country: "USA", home_team: "Seattle Mariners", primary_sport: "Baseball", primary_competition: "MLB", capacity: 47929, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/safeco17950.jpg")
Stadium.create(name: "RingCentral Coliseum", address: "", city: "Oakland", country: "USA", home_team: "Oakland Athletics", primary_sport: "Baseball", primary_competition: "MLB", capacity: 46765, image: "https://www.mercurynews.com/wp-content/uploads/2020/04/SJM-L-NFLNEWSOM-0405-3-1.jpg?w=640")
Stadium.create(name: "Oriole Park", address: "", city: "Baltimore", country: "USA", home_team: "Baltimore Orioles", primary_sport: "Baseball", primary_competition: "MLB", capacity: 45971, image: "http://ballparkdigest.com/wp-content/uploads/2019/11/Oriole-Park-at-Camden-6-15.jpg")
Stadium.create(name: "Angel Stadium", address: "", city: "Anaheim", country: "USA", home_team: "Los Angeles Angels", primary_sport: "Baseball", primary_competition: "MLB", capacity: 45517, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/02/angel15955.jpg")
Stadium.create(name: "Busch Stadium", address: "", city: "St. Louis", country: "USA", home_team: "St. Louis Cardinals", primary_sport: "Baseball", primary_competition: "MLB", capacity: 45494, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/busch17951.jpg")
Stadium.create(name: "Citizens Bank Park", address: "", city: "Philadelphia", country: "USA", home_team: "Philadelphia Phillies", primary_sport: "Baseball", primary_competition: "MLB", capacity: 42792, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/citbank_topv2.jpg")
Stadium.create(name: "Tropicana Field", address: "", city: "St. Petersburg", country: "USA", home_team: "Tampa Bay Rays", primary_sport: "Baseball", primary_competition: "MLB", capacity: 42735, image: "https://parkingaccess.com/blog/wp-content/uploads/2020/03/tropicana-field-parking.jpg")
Stadium.create(name: "Great American Ball Park", address: "", city: "Cincinnati", country: "USA", home_team: "Cincinnati Reds", primary_sport: "Baseball", primary_competition: "MLB", capacity: 42319, image: "https://daktronics.files.wordpress.com/2019/12/cincinnati-reds-bid-wideshot-opt-2.jpg")
Stadium.create(name: "Citi Field", address: "", city: "New York City", country: "USA", home_team: "New York Mets", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41922, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/citi17951.jpg")
Stadium.create(name: "American Family Field", address: "", city: "Milwaukee", country: "USA", home_team: "Milwaukee Brewers", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41900, image: "https://shepherdexpress.com/downloads/44462/download/11974696425_085e58e211_k.jpg?cb=bfd8141362758e208fb7f3365fef27b2&w=2048")
Stadium.create(name: "Wrigley Field", address: "", city: "Chicago", country: "USA", home_team: "Chicago Cubs", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41649, image: "https://static.onecms.io/wp-content/uploads/sites/39/2018/04/20222934/103219363_w.jpg")
Stadium.create(name: "Nationals Park", address: "", city: "Washington D.C.", country: "USA", home_team: "Washington Nationals", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41339, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/nats17_top.jpg")
Stadium.create(name: "Oracle Park", address: "", city: "San Francisco", country: "USA", home_team: "San Francisco Giants", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41265, image: "https://pbs.twimg.com/media/Ei5zho1U8AE0NSd.jpg")
Stadium.create(name: "Minute Maid Park", address: "", city: "Houston", country: "USA", home_team: "Houston Astros", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41168, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/minute_topv3.jpg")
Stadium.create(name: "Truist Park", address: "", city: "Cumberland", country: "USA", home_team: "Atlanta Braves", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41084, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/04/suntrust17951-2.jpg")
Stadium.create(name: "Comerica Park", address: "", city: "Detroit", country: "USA", home_team: "Detroit Tigers", primary_sport: "Baseball", primary_competition: "MLB", capacity: 41083, image: "https://www.gannett-cdn.com/presto/2019/04/04/PDTF/bb7bf4ff-1c47-435d-b4ea-3df289d0e880-openingday_040419_kpm_1082.jpg")
Stadium.create(name: "Guaranteed Rate Field", address: "", city: "Chicago", country: "USA", home_team: "Chicago White Sox", primary_sport: "Baseball", primary_competition: "MLB", capacity: 40615, image: "https://upload.wikimedia.org/wikipedia/commons/e/e2/U.S._Cellular_Field_%2830972191694%29.jpg")
Stadium.create(name: "Globe Life Field", address: "", city: "Arlington", country: "USA", home_team: "Texas Rangers", primary_sport: "Baseball", primary_competition: "MLB", capacity: 40300, image: "https://www.sportsvideo.org/new/wp-content/uploads/2020/07/Featured-scaled-e1595435594936.jpg")
Stadium.create(name: "Petco Park", address: "", city: "San Diego", country: "USA", home_team: "San Diego Padres", primary_sport: "Baseball", primary_competition: "MLB", capacity: 40209, image: "https://media.cbs8.com/assets/KFMB/images/89d75e1b-54ac-4d31-a0e4-cbde72cf084b/89d75e1b-54ac-4d31-a0e4-cbde72cf084b_750x422.jpg")
Stadium.create(name: "PNC Park", address: "", city: "Pittsburgh", country: "USA", home_team: "Pittsburgh Pirates", primary_sport: "Baseball", primary_competition: "MLB", capacity: 38747, image: "https://cdn.vox-cdn.com/thumbor/FMlQx_ct_wqIExeJABhQ17ag4-c=/0x0:1280x826/1200x800/filters:focal(532x349:736x553)/cdn.vox-cdn.com/uploads/chorus_image/image/66079222/image00000007.0.jpeg")
Stadium.create(name: "Target Field", address: "", city: "Minneapolis", country: "USA", home_team: "Minnesota Twins", primary_sport: "Baseball", primary_competition: "MLB", capacity: 38544, image: "http://ballparkdigest.com/wp-content/uploads/2019/05/targetfield2019-6.jpg")
Stadium.create(name: "Kauffman Stadium", address: "", city: "Kansas City", country: "USA", home_team: "Kansas City Royals", primary_sport: "Baseball", primary_competition: "MLB", capacity: 37903, image: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/03/kauff15952.jpg")
Stadium.create(name: "Fenway Park", address: "", city: "Boston", country: "USA", home_team: "Boston Red Sox", primary_sport: "Baseball", primary_competition: "MLB", capacity: 37755, image: "https://usatodayhss.com/wp-content/uploads/sites/96/2019/04/usatsi_12528069-e1555258744291.jpg?crop=0px%2C716px%2C4585px%2C2750px&resize=1000%2C600")
Stadium.create(name: "loanDepot Park", address: "", city: "Miami", country: "USA", home_team: "Miami Marlins", primary_sport: "Baseball", primary_competition: "MLB", capacity: 37442, image: "https://www.baseballpilgrimages.com/national/miami.jpg")
Stadium.create(name: "Progressive Field", address: "", city: "Cleveland", country: "USA", home_team: "Cleveland Indians", primary_sport: "Baseball", primary_competition: "MLB", capacity: 35041, image: "https://ewscripps.brightspotcdn.com/dims4/default/b00ce73/2147483647/strip/true/crop/5983x3366+4+351/resize/1280x720!/quality/90/?url=http%3A%2F%2Fewscripps-brightspot.s3.amazonaws.com%2F6c%2F9f%2F359a1c8642e4b1c7f574bb52bdb0%2F20180524-dsc0515.jpg")

# NBA


# MLS


################################
# Test visits
# Visit.create(user_id: 1, stadium_id: 6, team_1: "Liverpool", team_2: "West Brom", date: 10/20/2016, competition: "Premier League", team_1_score: 4, team_2_score: 0, sport: "soccer")
# Visit.create(user_id: 1, stadium_id: 6, team_1: "Liverpool", team_2: "Watford", date: 10/20/2016, competition: "Premier League", team_1_score: 4, team_2_score: 0, sport: "soccer")
# Visit.create(user_id: 3, stadium_id: 1, team_1: "Manchester City", team_2: "Liverpool", date: 10/05/2016, competition: "Premier League", team_1_score: 3, team_2_score: 4, sport: "soccer")