# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).

# Blank Stadium: Stadium.create(name: "", address: "", city: "", country: "", home_team: "", primary_sport: "", primary_competition: "", capacity: , image: "")
# Premier League
Stadium.create(name: "Etihad Stadium", address: "Ashton New Rd, Manchester M11 3FF, United Kingdom", city: "Manchester", country: "United Kingdom", home_team: "Manchester City", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 55017, image: "https://www.thestadiumbusiness.com/wp-content/uploads/2019/10/Etihad_Stadium-1-3.jpg")
Stadium.create(name: "Old Trafford", address: "Sir Matt Busby Way, Old Trafford, Stretford, Manchester M16 0RA, United Kingdom", city: "Manchester", country: "United Kingdom", home_team: "Manchester United", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 75643, image: "https://img.fifa.com/image/upload/t_l1/c66wodrhc27coham0zkz.jpg")
Stadium.create(name: "Stamford Bridge", address: "Fulham Rd, London SW6 1HS, United Kingdom", city: "London", country: "United Kingdom", home_team: "Chelsea", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 40834, image: "https://images2.minutemediacdn.com/image/fetch/w_736,h_485,c_fill,g_auto,f_auto/https%3A%2F%2Ftheprideoflondon.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2016%2F03%2F514524892-chelsea-fc-v-paris-saint-germain-uefa-champions-league-850x560.jpg")
Stadium.create(name: "King Power Stadium", address: "Filbert Way, Leicester LE2 7FL, United Kingdom", city: "Leicester", country: "United Kingdom", home_team: "Leicester City", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32261, image: "https://www.leicestercity.net/wp-content/uploads/2020/11/king-power.jpg")
Stadium.create(name: "London Stadium", address: "London E20 2ST, United Kingdom", city: "London", country: "United Kingdom", home_team: "West Ham", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 60000, image: "https://res.cloudinary.com/london-stadium/image/upload/assets/main_image/1595350248_graciolli_img_8022-hdr.jpg")
Stadium.create(name: "Anfield", address: "Anfield Rd, Anfield, Liverpool L4 0TH, United Kingdom", city: "Liverpool", country: "United Kingdom", home_team: "Liverpool", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 54074, image: "https://i.ytimg.com/vi/6-83IeF56r4/maxresdefault.jpg")
Stadium.create(name: "Tottenham Hotspur Stadium", address: "782 High Rd, London N17 0BX, United Kingdom", city: "London", country: "United Kingdom", home_team: "Tottenham Hotspur", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 62214, image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Tottenham_Hotspur_Stadium_South_Stand.jpg")
Stadium.create(name: "Villa Park", address: "Trinity Rd, Birmingham B6 6HE, United Kingdom", city: "Birmingham", country: "United Kingdom", home_team: "Aston Villa", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 42749, image: "https://i.guim.co.uk/img/media/4b89d8784cbd2bc089c1229cf5285ba276c177b2/0_339_5095_3057/master/5095.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=e4a2f64db8b09ba3f167099d37a04173")
Stadium.create(name: "St. James' Park", address: "Barrack Rd, Newcastle upon Tyne NE1 4ST, United Kingdom", city: "Newcastle upon Tyne", country: "United Kingdom", home_team: "Newcastle United", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 52305, image: "https://www.nufc.co.uk/media/24154/st-james-hero-image.jpg?anchor=center&mode=crop&width=900&height=506&quality=75")
Stadium.create(name: "Craven Cottage", address: "Stevenage Rd, London SW6 6HH, United Kingdom", city: "London", country: "United Kingdom", home_team: "Fulham", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 25700, image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Craven_Cottage_stadium_view.jpg")
# Stadium.create(name: "Turf Moor", address: "52-56 Harry Potts Way, Burnley BB10 4BX, United Kingdom", city: "Burnley", country: "United Kingdom", home_team: "Burnley", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 21944, image: "")
# Stadium.create(name: "Goodison Park", address: "Goodison Rd, Liverpool L4 4EL, United Kingdom", city: "Liverpool", country: "United Kingdom", home_team: "Everton", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 39414, image: "")
# Stadium.create(name: "Selhurst Park", address: "Whitehorse Ln, London SE25 6PU, United Kingdom", city: "London", country: "United Kingdom", home_team: "Crystal Palace", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 25486, image: "")
# Stadium.create(name: "Emirates Stadium", address: "Hornsey Rd, London N7 7AJ, United Kingdom", city: "London", country: "United Kingdom", home_team: "Arsenal", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 60704, image: "")
# Stadium.create(name: "Molineux Stadium", address: "Waterloo Rd, Wolverhampton WV1 4QR, United Kingdom", city: "Wolverhampton", country: "United Kingdom", home_team: "Wolves", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32050, image: "")
# Stadium.create(name: "Elland Road", address: "Elland Rd, Beeston, Leeds LS11 0ES, United Kingdom", city: "Leeds", country: "United Kingdom", home_team: "Leeds", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 37792, image: "")
# Stadium.create(name: "The American Express Community Stadium", address: "Village Way, Brighton BN1 9BL, United Kingdom", city: "Brighton", country: "United Kingdom", home_team: "Brighton", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 30750, image: "")
# Stadium.create(name: "St. Mary's Stadium", address: "Britannia Rd, Southampton SO14 5FP, United Kingdom", city: "Southampton", country: "United Kingdom", home_team: "Southampton", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32384, image: "")
# Stadium.create(name: "The Hawthorns", address: "West Bromwich B71 4LF, United Kingdom", city: "West Bromwich", country: "United Kingdom", home_team: "West Brom", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 26445, image: "")
# Stadium.create(name: "Bramall Lane", address: "Bramall Ln, Highfield, Sheffield S2 4SU, United Kingdom", city: "Sheffield", country: "United Kingdom", home_team: "Sheffield United", primary_sport: "Soccer", primary_competition: "Premier League", capacity: 32702, image: "")
# MLB
# MLS
# NBA